---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: nginx-ingress-external
  namespace: ingress
spec:
  chart:
    version: 1.36.0
  values:
    controller:
      electionID: ingress-controller-leader-external
      ingressClass: nginx-external
      replicaCount: 1
    defaultBackend:
      replicaCount: 1
      # service:
      #   annotations:
      #     cloud.google.com/load-balancer-type: "Internal"
      #     networking.gke.io/internal-load-balancer-allow-global-access: "true"
      #     # https://cloud.google.com/kubernetes-engine/docs/how-to/ingress-features
      #     cloud.google.com/backend-config: '{"default": "backendconfig"}'