apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: nginx-ingress-external
  namespace: ingress
spec:
  helmVersion: v3
  releaseName: nginx-ingress-external
  chart:
    repository: https://kubernetes-charts.storage.googleapis.com/
    name: nginx-ingress
    version: 1.33.4
  valuesFrom:
  # Base values for all environments
  - configMapKeyRef:
      name: helmrelease-base-values
      key: base-values.yaml
      optional: false
  # This environment specific values
  - configMapKeyRef:
      name: helmrelease-env-values
      key: values.yaml
      optional: false
