apiVersion: v1
kind: ConfigMap
metadata:
  name: helmrelease-env-values
  namespace: ingress
data:
  values.yaml: |
    controller:
      electionID: ingress-controller-leader-external
      ingressClass: nginx-external
