apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-nginx-internal
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  # https://argoproj.github.io/argo-cd/user-guide/auto_sync/
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  source:
    repoURL: https://kubernetes.github.io/ingress-nginx
    chart: ingress-nginx
    targetRevision: 3.23.0
    helm:
      values: |
        controller:
          service:
            annotations:
              # Create internal LB
              cloud.google.com/load-balancer-type: "Internal"
  destination:
    server: https://kubernetes.default.svc
    namespace: ingress
