apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: aws-route53-credentials-secret
  namespace: cert-manager
spec:
  encryptedData:
    secret-access-key: AgBJL53fbcQtG4SO7z/XJz5jtSPrLdJ9JSr8S+LzGlHs/IM3U0XxWPUZ+JEgLFL5qxQB1nz0a+/Qb4HMyPPHERth5NIhxbgjsRzC1/SAnmzfiG08aYzn8dfwlB9dHF1+Kzw8poA24NqotcDp86XImAD3DzkCu+i02BHBrYVxUZcxntIlTVTTgoxWgeM/4QZCy0my7NxR6Np/+2CsQ3mQ4CWYB0yLu5+59vZ3J3EJV6w9rG8I2YRy0GT16rkuOBcjCNXt8CgZ30dx439CjwHK05vTHSChCth67ZDhmyDpsNBs4BVhLKD7bfiqQ0cMugNz2FbOTaZlYpfsYpp/TBV0RXLzg3i1yeZOZqo9Uvt1sBKtMAlLDztx8q+E0KdVzydO9tqwZkKCyMw4PfIFqOLlcllJB0fHN+UniZDsIOW5NZS/GZ1THVgJAy0fOs0y4Ce+VFvPs4ACYfvgisf/afqi0Cd8eD306CY7YCk2W3dNF5FIvnTdEwYYbVG8/0BwQqLTJbVoDWG3vfr33KsYVM51kqL6sCAQJeTjeVFI4g1WdSD/XzgZ5pJDcTttM9e/wvrYSLjuoiMAQ0MLh3+hhaz7Oj6ixXiobh7HjDlXbRJwwjsOxQ1UulGI7Yzajx1YAph6LbAerSkXnM4/rJk0YfsjVzldnX9aqdsXT2zLyUp6y6wb6MVcAOn1zuJnz+sZyR2ioOQLpjst8C5svD5WkIPijiWncAyS8E22lXBqsLmgwk+A7pBGrHBfTxPr
  template:
    metadata:
      creationTimestamp: null
      name: aws-route53-credentials-secret
      namespace: cert-manager
status: {}

