apiVersion: v1
kind: ConfigMap
metadata:
  name: helmrelease-base-values
  namespace: cert-manager
data:
  base-values.yaml: |
    controller:
      replicaCount: 2
      ## Name of the ingress class to route through this controller
      ##