---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: external-dns
  namespace: external-dns
spec:
  releaseName: external-dns
  chart:
    name: external-dns
    repository: https://kubernetes-charts.storage.googleapis.com/
    version: 2.5.3
  valuesFrom:
  # Base values for all environments
  - configMapKeyRef:
      name: helmrelease-base-values
      key: base-values.yaml
      optional: false
  # This environment specific values
  - configMapKeyRef:
      name: helmrelease-env-values
      key: values.yaml
      optional: false
