apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
- ../../../../../base/cert-manager/cert-manager/crds
patchesStrategicMerge:
- certificaterequests.yaml
- certificates.yaml
- challenges.yaml
- clusterissuers.yaml
- issuers.yaml
- orders.yaml
