---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: prometheus-operator
  namespace: monitoring
spec:
  helmVersion: v3
  releaseName: prometheus-operator
  chart:
    name: prometheus-operator
    version: 8.12.12
    repository: https://kubernetes-charts.storage.googleapis.com/
  valuesFrom:
  # Base values for all environments
  - configMapKeyRef:
      name: helmrelease-base-values
      key: base-values.yaml
      optional: false
  # This environment specific values
  - configMapKeyRef:
      name: helmrelease-env-values
      key: values.yaml
      optional: false
