---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- helmrelease.yaml
namespace: ingress
commonLabels:
  k8s.managedkube.com/path: kubernetes-releases-base-gcp-nginx-ingress
  k8s.managedkube.com/app: nginx-ingress
