---
apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: lyfted
  namespace: lyfted
spec:
  secretName: cert-manager-tls-cert
  issuerRef:
    kind: ClusterIssuer
    name: issuer-dns01
  dnsNames:
  - lyfted-1.dev.k8s.managedkube.com
