---
apiVersion: helm.toolkit.fluxcd.io/v2alpha1
kind: HelmRelease
metadata:
  name: sumologic
  namespace: monitoring
spec:
  chart:
    spec:
      # The Helm chart version
      version: 1.2.2
  values:
    sumologic:
      accessId: su5HxguCa08i9z
      accessKey: aVJDqIlfAuWmZIhcvSB7Nmr6NHAyQqgmovjIygqX9SFT1Y6lOyCxp2gFbDnVoFHv
      clusterName: dev-us
