---
apiVersion: helm.toolkit.fluxcd.io/v2alpha1
kind: HelmRelease
metadata:
  name: sumologic
  namespace: monitoring
spec:
  chart:
    spec:
      # The Helm chart version
      version: 1.2.2
  values:
    sumologic:
      accessId: xxx
      accessKey: xxx
      clusterName: dev-us
