
version: "3.8"
services:

  nginx-static:
    image: nginx:stable
    volumes:
      - ${PWD}/static-html:/usr/share/nginx/html:ro
    ports:
      - "8080:80"
    # networks:
    #   - frontend
    deploy:
      replicas: 1

  web:
    network_mode: host
    build: .
    ports:
      - "5000:5000"

  mysql:
    network_mode: host
    image: mysql:5.7
    volumes:
      - db-data:/var/lib/mysql
    restart: always
    ports:
      - 3306:3306
    environment:
      # MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_ROOT_PASSWORD: somewordpress
      MYSQL_DATABASE: garland
      MYSQL_USER: garland
      MYSQL_PASSWORD: garland

volumes:
  db-data:
