---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: kube-metrics-adapter
  namespace: kube-system
spec:
  helmVersion: v3
  releaseName: kube-metrics-adapter
  chart:
    git: git@github.com:ManagedKube/kubernetes-ops.git
    path: kubernetes/helm/kube-metrics-adapter
    ref: master
    version: v0.1.0
  values:
    {}
