---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: cluster-issuer
  namespace: cert-manager
spec:
  helmVersion: v3
  releaseName: cluster-issuer
  chart:
    git: git@github.com:ManagedKube/kubernetes-ops.git
    path: kubernetes/helm/cert-manager/cluster-issuer
    ref: master
    version: v0.14.0
  values:
    provider: google

    email: devops+gcp-dev@managedkube.com

    # Google Cloud DNS
    clouddns:
      # The ID of the GCP project
      project: managedkube
      # This is the secret used to access the service account
      # The file name has to be "credentials.json".  The file name is put into the secret
      # as the key name and the chart is looking for the key name "credentials.json"
      # kubectl -n cert-manager create secret generic clouddns-dns01-solver-svc-acct --from-file=credentials.json
      # Doc: https://cert-manager.io/docs/configuration/acme/dns01/google/#set-up-a-service-account
      serviceAccountSecretRef:
        name: "clouddns-dns01-solver-svc-acct"
        key: credentials.json

    issuer:
      dns:
        enabled: true
        name: issuer-dns01

      http:
        enabled: true
        name: issuer-http01
