---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: external-dns
  namespace: external-dns
spec:
  chart:
    version: 2.21.2
  values:
    ## The dns provider
    provider: aws

    txtOwnerId: "k8s-aws-staging"

    ## List of domains that can be managed
    domainFilters: ["dev.managedkube.com"]

    ## AWS configuration to be set via arguments/env. variables
    ##
    aws:
      ## AWS credentials
      ##
      credentials:
        secretName: credentials
