---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: cluster-issuer
  namespace: cert-manager
spec:
  helmVersion: v3
  releaseName: cluster-issuer
  chart:
    git: git@github.com:ManagedKube/kubernetes-ops.git
    path: kubernetes/helm/cert-manager/cluster-issuer
    ref: master
    version: v0.1.1
  values:
    provider: aws

    email: devops+aws-dev@managedkube.com

    aws:
      region: us-east-1
      accessKeyID: AKIA4FAGGAABV3VDZCMF
      accessSecret: "secret"
      accessSecretFromManualSecretCreation: true

    issuer:
      dns:
        enabled: true
        name: issuer-dns01

      http:
        enabled: true
        name: issuer-http01
