apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: credentials
  namespace: external-dns
spec:
  encryptedData:
    credentials: AgBQ+HWNyHoxM4ctQ27DJmA2XYRhzE9pfjj0X1g/5voDhcsSwuF+h40vt1uJkrTsmmlwEyfOpfz2M18qmrgo7VyM7uY6v7ofzEYOGFQ6sFq/lhQYwsMS+Ov3hdLkGHZGep99d9PKXOyfZILRUtdGGvQWEMjOvSIpzd8Rf6MwXioVfS29GJHe9dWBzVaGz8GlA1f6Ii0xgG3LWHkdNuMPTVXa4GZXFW/gqes0PVR9Ml4rzbVZtTWncxZWb6WT4+LHaqd9310483Zmwaz5hAPecNR166LuABCHwRKZ9+8TfrI1C0i61I87UvK1m2hEZukdy1XeJep8H2PJnLpVvBjFVwKlO/VR1zTZ+/Ii6gIBDAnwTI0ahLKnApajU3r3I4PQlS4sOrBUsAHiK7v2Bb0x5ESuoqKdaZ5N5IIt9yFUTU7LOlSrIEMoghB7YRyMONNnWHsVB2xuE5w72y9boNgueJKYZRediiro8Bw1uwyxb840e/MzmWr6bWoD61klWjBDgqCo3zpM8C3HjZRUFvJo4ShLEUTnKdHJrBP/Wc2H/F5QNjSFL9ANmEuG9LoL2qKKMHSfTlug/VdO8h1aUYhLRhrHGrY4sCuQu7PKIffP8AD3C2pYJU9SGUlMUf9bFZ4++Kh85OxUBkQJNjy7KEduN/w7Fjk2h5dLed5GzQehN2bVVbfK8EHZUOvtrs34FMXIgBZB9up9Jj7Ts9qWYeN1o74J6fgwhOO9EHKwU5fCUK5VkcTf6GMWqmOebZiymOctoMuR7DOG4wZoZGm0u26kBIKLpSYAF0pWY0s8yyNR12TuJFx+uzCEwCk41Ctceq9cwUxB6r5U+1JQMRhHwKNmvXqT
  template:
    metadata:
      creationTimestamp: null
      name: credentials
      namespace: external-dns
status: {}

