---
apiVersion: helm.toolkit.fluxcd.io/v2alpha1
kind: HelmRelease
metadata:
  name: sumologic
spec:
  interval: 1m
  # helmVersion: v3
  releaseName: sumologic
  chart:
    spec:
      chart: sumologic
      version: 1.2.2
      interval: 1m
      sourceRef:
        kind: HelmRepository
        name: sumologic
        namespace: gitops-system
  values:
    # Falco settings: https://github.com/SumoLogic/sumologic-kubernetes-collection/blob/master/deploy/helm/sumologic/values.yaml#L1376
    falco:
      enabled: true
    # This is using the kube-prometheus-stack chart
    # https://github.com/prometheus-community/helm-charts/blob/main/charts/kube-prometheus-stack/values.yaml
    prometheus-operator:
      prometheusOperator:
        enabled: false
      nodeExporter:
        enabled: true
      prometheus-node-exporter:
        # If you have another prometheus node exporter running, it is probably on port 9100.  This sets
        # The port to another port so they dont collide
        service:
          port: 49100
          targetPort: 49100      
      kubelet:
        serviceMonitor:
          https: false
      kubeProxy:
        enabled: false