apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: cluster-issuer
  namespace: cert-manager
spec:
  releaseName: cluster-issuer
  chart:
    git: git@github.com:ManagedKube/kubernetes-ops.git
    path: kubernetes/helm/cert-manager/cluster-issuer
    ref: master
    version: v0.14.0
  valuesFrom:
  - chartFileRef:
      # path within the helm chart (from git repo) where the file is located.  E.g path from the spec.chart.path location.  Not from the Git repo root.
      path: values.yaml
      optional: false    
  - chartFileRef:
      # path within the helm chart (from git repo) where the file is located.  E.g path from the spec.chart.path location.  Not from the Git repo root.
      path: ../../../flux/releases/gcp/dev/cert-manager/cluster-issuer/values.yaml
      optional: false
