apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
- ../../../../base/cert-manager/cluster-issuer/
resources:
- clouddns-dns01-solver-svc-acct.yaml
patchesStrategicMerge:
- helmrelease.yaml
