name: pr_kustomize_output_check_aws_dev
# This workflow is triggered on pushes to the repository.
on:
  pull_request:
    branches:
      - master

# Environment variables available to all jobs and steps in this workflow
env:
  KUSTOMIZE_DOWNLOAD_URL: "https://github.com/kubernetes-sigs/kustomize/releases/download"
  KUSTOMIZE_VERSION: "v3.5.5"
  KUSTOMIZE_BUILD_PATH: "./kubernetes/flux/releases/aws/dev"

jobs:
  build:
    # Job name is Update
    name: checks
    # This job runs on Linux
    runs-on: ubuntu-18.04
    steps:
      # Checkout the repository
      - name: Checkout
        uses: actions/checkout@v1
      # Set up kops
      - name: Set up kustomize
        run: |
          curl -o kustomize_${KUSTOMIZE_VERSION}_linux_amd64.tar.gz --location ${KUSTOMIZE_DOWNLOAD_URL}/kustomize%2F${KUSTOMIZE_VERSION}/kustomize_${KUSTOMIZE_VERSION}_linux_amd64.tar.gz
          tar -zxvf kustomize_${KUSTOMIZE_VERSION}_linux_amd64.tar.gz
          chmod u+x ./kustomize
          export PATH=$(pwd):$PATH
          kustomize version
      - name: Run kustomize check
        run: |
          export PATH=$(pwd):$PATH
          kustomize build ${KUSTOMIZE_BUILD_PATH}
