---
flux:
  # If enabled, fluxd will delete resources that it created, but are no longer present in git
  syncGarbageCollection:
    enabled: true
  # Enables running Kustomize
  manifestGeneration: true
